services:
  mongodb-primary:
    image: mongo:latest
    container_name: mongodb-primary
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: absApp
      MONGO_INITDB_ROOT_PASSWORD: EjcD8437nWN32zG05q6G19
    ports:
      - "27017:27017"
    volumes:
      - C:\PROJECTS\abs\storages\mongodo\node1:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./keyfile:/etc/keyfile      
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 14G
        reservations:
          cpus: '2'
          memory: 14G
    command: mongod --config /etc/mongod.conf
  mongodb-secondary-1:
    image: mongo:latest
    container_name: mongodb-secondary-1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: absApp
      MONGO_INITDB_ROOT_PASSWORD: EjcD8437nWN32zG05q6G19
    ports:
      - "27018:27017"
    volumes:
      - C:\PROJECTS\abs\storages\mongodo\node2:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./keyfile:/etc/keyfile

    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 14G
        reservations:
          cpus: '2'
          memory: 14G
    command: mongod --config /etc/mongod.conf
  mongodb-secondary-2:
    image: mongo:latest
    container_name: mongodb-secondary-2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: absApp
      MONGO_INITDB_ROOT_PASSWORD: EjcD8437nWN32zG05q6G19
    ports:
      - "27019:27017"
    volumes:
      - C:\PROJECTS\abs\storages\mongodo\node3:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./keyfile:/etc/keyfile

    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 14G
        reservations:
          cpus: '2'
          memory: 14G
    command: mongod --config /etc/mongod.conf

