services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: absApp
      MONGO_INITDB_ROOT_PASSWORD: EjcD8437nWN32zG05q6G19
    ports:
      - "27017:27017"
    volumes:
      - /gpgames-data/mongodb-data:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 14G
        reservations:
          cpus: '2'
          memory: 14G
    command: mongod --config /etc/mongod.conf

