services:

  rabbitmq:
    image: rabbitmq:4.1-rc-alpine
    container_name: abs-rabbitmq_service
    ports:
      - "5672:5672"    # RabbitMQ main port for communication
      - "5070:15672"   # RabbitMQ management web UI
    environment:
      - RABBITMQ_DEFAULT_USER=abs_app  # Default username for RabbitMQ
      - RABBITMQ_DEFAULT_PASS=EjcD8437nWN32zG05q6G19  # Default password for RabbitMQ
      - TZ=Asia/Dhaka
    deploy:
      resources:
        limits:
          memory: 8G       # Limit memory usage to 1GB
          cpus: '1'      # Limit CPU usage to 1.5 core
#    storage_opt:
#      size: "1G"     # Limit disk usage to 1GB
    restart: always
    volumes:
      - /Users/mehedimayall/PROJECTS/Database/abs/rabbitmq:/var/lib/rabbitmq  # Map RabbitMQ data to the host directory
