services:
  postgres:
    image: postgres:17-alpine3.20
    labels:
      - abs-postgres
    container_name: abs-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=EjcD8437nWN32zG05q6G19
      - POSTGRES_USER=abs_app
      - POSTGRES_DB=postgres
      - TZ=Asia/Dhaka
    restart: always
    volumes:
      - /Users/mehedimayall/PROJECTS/Database/abs/postgresql-data:/var/lib/postgresql/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

    deploy:
      resources:
        limits:
          memory: 8G       # Limit memory usage to 1GB
          cpus: '4'      # Limit CPU usage to 1.5 core
        reservations:
          cpus: '4'
          memory: 8G

 
          
          
          