@host = http://localhost:3300



### Patient Add
POST {{host}}/patient/add
Content-Type: application/json


{
  "firstName": "Ibrahim",
  "lastName": "Hasan",
  "dateOfBirth": "1985-05-15",
  "gender": "Male",
  "bloodType": "A+",
  "address": {
    "city": "Gazipur",
    "country": "BD"
  },
  "contactInfo": {
    "phone": "2345154535056",
    "secondaryPhone": "555-987-6543",
    "email": "ibrahim@gmail.com"
  },
  "emergencyContacts": [
    {
      "name": "Rita Hasan",
      "relationship": "Spouse",
      "phone": "555-234-5678",
      "priority": 1
    },
    {
      "name": "Arshad Hasan",
      "relationship": "Father",
      "phone": "555-345-6789",
      "priority": 2
    }
  ],
  "insuranceInfo": {
    "provider": "Blue Cross",
    "policyNumber": "BC123456789",
    "groupNumber": "GRP987654",
    "expirationDate": "2025-12-31T00:00:00Z"
  }

}